name: Bug report
description: Report a reproducible bug to help us improve
title: "Bug: TITLE"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report. Please add as much information as possible to help us reproduce, and remove any potential sensitive data.
  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
      description: Please share details on the behaviour you expected
    validations:
      required: true
  - type: textarea
    id: current_behaviour
    attributes:
      label: Current Behaviour
      description: Please share details on the current issue
    validations:
      required: true
  - type: textarea
    id: code_snippet
    attributes:
      label: Code snippet
      description: Please share a code snippet to help us reproduce the issue
      render: python
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: If known, please suggest a potential resolution
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please share how we might be able to reproduce this issue
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: AWS Lambda Powertools for Python version
      placeholder: "latest, 1.25.6"
      value: latest
    validations:
      required: true
  - type: dropdown
    id: runtime
    attributes:
      label: AWS Lambda function runtime
      options:
        - label: "3.6"
        - label: "3.7"
        - label: "3.8"
        - label: "3.9"
    validations:
      required: true
  - type: dropdown
    id: packaging
    attributes:
      label: Packaging format used
      options:
        - label: "Lambda Layers"
        - label: "Serverless Application Repository (SAR) App"
        - label: "PyPi"
      multiple: true
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Debugging logs
      description: If available, please share [debugging logs](https://awslabs.github.io/aws-lambda-powertools-python/#debug-mode)
      render: python
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.
