name: Support Powertools for AWS Lambda (Python) (become a reference)
description: Add your organization's name or logo to the Powertools for AWS Lambda (Python) documentation
title: "[Support Powertools for AWS Lambda (Python)]: <your organization name>"
labels: ["customer-reference"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for becoming a reference customer. Your support means a lot to us. It also helps new customers to know who's using it.

        If you would like us to also display your organization's logo, please share a link in the `Company logo` field.
  - type: input
    id: organization
    attributes:
      label: Organization Name
      description: Please share the name of your organization
      placeholder: ACME
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Your Name
      description: Please share your name
    validations:
      required: true
  - type: input
    id: job
    attributes:
      label: Your current position
      description: Please share your current position at your company
    validations:
      required: true
  - type: input
    id: logo
    attributes:
      label: (Optional) Company logo
      description: Company logo you want us to display. You also allow us to resize for optimal placement in the documentation.
    validations:
      required: false
  - type: textarea
    id: use_case
    attributes:
      label: (Optional) Use case
      description: How are you using Powertools for AWS Lambda (Python) today? *features, etc.*
    validations:
      required: false
  - type: checkboxes
    id: other_languages
    attributes:
      label: Also using other Powertools for AWS Lambda languages?
      options:
        - label: Java
          required: false
        - label: TypeScript
          required: false
        - label: .NET
          required: false
  - type: markdown
    attributes:
      value: |
        *By raising a Support Powertools for AWS Lambda (Python) issue, you are granting AWS permission to use your company's name (and/or logo) for the limited purpose described here. You are also confirming that you have authority to grant such permission.*

        *You can opt-out at any time by commenting or reopening this issue.*
