[GLOBAL]
pants_version = "2.21.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.typecheck.mypy",
]

[python]
interpreter_constraints = [">=3.10,<3.14"]

[python-infer]
use_rust_parser = true

[source]
root_patterns = ["/"]
