DEFAULT_API_VERSION = "1.0.0"
DEFAULT_OPENAPI_VERSION = "3.1.0"
DEFAULT_OPENAPI_TITLE = "Powertools for AWS Lambda (Python) API"
DEFAULT_CONTENT_TYPE = "application/json"
DEFAULT_OPENAPI_RESPONSE_DESCRIPTION = "Successful Response"
DEFAULT_STATUS_CODE = 200
