# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 30, 2, "", "user_prof.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fuser_prof.proto\x12\x14\x63om.example.protobuf"4\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0b\n\x03zip\x18\x03 \x01(\t"\xb7\x02\n\x0bUserProfile\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x10\n\x08isActive\x18\x05 \x01(\x08\x12\x12\n\nsignupDate\x18\x06 \x01(\t\x12\x0c\n\x04tags\x18\x07 \x03(\t\x12\r\n\x05score\x18\x08 \x01(\x01\x12G\n\x0bpreferences\x18\t \x03(\x0b\x32\x32.com.example.protobuf.UserProfile.PreferencesEntry\x12.\n\x07\x61\x64\x64ress\x18\n \x01(\x0b\x32\x1d.com.example.protobuf.Address\x1a\x32\n\x10PreferencesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3',  # noqa: E501
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user_prof_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USERPROFILE_PREFERENCESENTRY"]._loaded_options = None
    _globals["_USERPROFILE_PREFERENCESENTRY"]._serialized_options = b"8\001"
    _globals["_ADDRESS"]._serialized_start = 41
    _globals["_ADDRESS"]._serialized_end = 93
    _globals["_USERPROFILE"]._serialized_start = 96
    _globals["_USERPROFILE"]._serialized_end = 407
    _globals["_USERPROFILE_PREFERENCESENTRY"]._serialized_start = 357
    _globals["_USERPROFILE_PREFERENCESENTRY"]._serialized_end = 407
# @@protoc_insertion_point(module_scope)
