name: Quality check - Build docs

# PROCESS
#
# 1. Install all dependencies required to build the docs
# 2. Build the docs

# USAGE
#
# Always triggered on new PRs, PR changes and PR merge.


on:
  pull_request:
    paths:
      - "docs/**"
      - "examples/**"
      - "mkdocs.yml"
    branches:
      - develop
  push:
    paths:
      - "docs/**"
      - "examples/**"
      - "mkdocs.yml"
    branches:
      - develop

permissions:
  contents: read

jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # checkout code only
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.14
      - name: Install doc generation dependencies
        run: |
          cat docs/requirements.txt
          pip install --require-hashes -r docs/requirements.txt
      - name: Build docs
        run: |
          rm -rf site
          mkdocs build
