name: Code quality - CDK constructor

# PROCESS
#
# 1. Install all dependencies and spin off containers for all supported Python versions
# 2. Run code formatters and linters (various checks) for code standard
# 3. Run static typing checker for potential bugs
# 4. Run tests

# USAGE
#
# Always triggered on new PRs, PR changes and PR merge.


on:
  pull_request:
    paths:
      - "layer_v3/layer_constructors/**"
    branches:
      - develop
  push:
    paths:
        - "layer_v3/layer_constructors/**"
    branches:
      - develop

permissions:
  contents: read

jobs:
  quality_check_cdk:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.14"]
    env:
      PYTHON: "${{ matrix.python-version }}"
    permissions:
      contents: read  # checkout code only
    defaults:
      run:
        working-directory: ./layer_v3/layer_constructors
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v2.0.0
        with:
          platforms: arm64
        # NOTE: we need QEMU to build Layer against a different architecture (e.g., ARM)
      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
        with:
          install: true
          driver: docker
          platforms: linux/amd64,linux/arm64
      - name: Install dependencies
        run: |
            pip install --upgrade pip pre-commit poetry
            poetry install
      - name: Test with pytest
        run: poetry run pytest tests
