name: Quality check - Build docs

# PROCESS
#
# 1. Install all dependencies required to build the docs
# 2. Build the docs

# USAGE
#
# Always triggered on new PRs, PR changes and PR merge.


on:
  pull_request:
    paths:
      - "docs/**"
      - "examples/**"
      - "mkdocs.yml"
    branches:
      - develop
  push:
    paths:
      - "docs/**"
      - "examples/**"
      - "mkdocs.yml"
    branches:
      - develop

permissions:
  contents: read

jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # checkout code only
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14
      - name: Install doc generation dependencies
        run: |
          cat docs/requirements.txt
          pip install --require-hashes -r docs/requirements.txt
      - name: Build docs
        run: |
          rm -rf site
          mkdocs build
