name: Deploy V3 SAR

# PROCESS
#
# 1. This workflow starts after the layer artifact is produced on `publish_v3_layer`
# 2. We use the same layer artifact to ensure the SAR app is consistent with the published Lambda Layer
# 3. We publish the SAR for 3.8 to 3.12 Python runtime and both x86_64 and arm64 (see `matrix` section)
# 4. We use `sam package` and `sam publish` to publish the SAR app
# 5. We remove the previous Canary stack (if present) and deploy a new one to test the SAR App. We retain the Canary in the account for debugging purposes
# 6. Finally the published SAR app is made public on the PROD environment

# USAGE
#
# NOTE: meant to be used with ./.github/workflows/publish_v3_layer.yml
#
# sar-beta:
#   needs: build-layer
#   permissions:
#     # lower privilege propagated from parent workflow (release.yml)
#     id-token: write
#     contents: read
#     pull-requests: none
#     pages: none
#   uses: ./.github/workflows/reusable_deploy_v3_sar.yml
#   secrets: inherit
#   with:
#     stage: "BETA"
#     environment: "layer-beta"
#     package-version: ${{ inputs.latest_published_version }}
#     source_code_artifact_name: ${{ inputs.source_code_artifact_name }}
#     source_code_integrity_hash: ${{ inputs.source_code_integrity_hash }}

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: 18.20.4
  AWS_REGION: eu-west-1
  SAR_NAME: aws-lambda-powertools-python-layer-v3
  TEST_STACK_NAME: serverlessrepo-v3-powertools-layer-test-stack
  RELEASE_COMMIT: ${{ github.sha }}  # it gets propagated from the caller for security reasons

on:
  workflow_call:
    inputs:
      stage:
        description: "Deployment stage (BETA, PROD)"
        required: true
        type: string
      package-version:
        description: "The version of the package to deploy"
        required: true
        type: string
      environment:
        description: "GitHub Environment to use for encrypted secrets"
        required: true
        type: string
      source_code_artifact_name:
        description: "Artifact name to restore sealed source code"
        type: string
        required: true
      source_code_integrity_hash:
        description: "Sealed source code integrity hash"
        type: string
        required: true

jobs:
  deploy-sar-app:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        architecture: ["x86_64", "arm64"]
        python-version: ["3.8","3.9","3.10","3.11","3.12"]
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          ref: ${{ env.RELEASE_COMMIT }}

      - name: Restore sealed source code
        uses: ./.github/actions/seal-restore
        with:
          integrity_hash: ${{ inputs.source_code_integrity_hash }}
          artifact_name: ${{ inputs.source_code_artifact_name }}


      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_LAYERS_ROLE_ARN }}

      # NOTE
      # We connect to Layers account to log our intent to publish a SAR Layer
      # we then jump to our specific SAR Account with the correctly scoped IAM Role
      # this allows us to have a single trail when a release occurs for a given layer (beta+prod+SAR beta+SAR prod)
      - name: AWS credentials SAR role
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        id: aws-credentials-sar-role
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          role-duration-seconds: 1200
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_SAR_V2_ROLE_ARN }}
      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: cdk-layer-artifact-py${{ matrix.python-version }}
      - name: Unzip artefact
        run: unzip cdk.py${{ matrix.python-version }}.out.zip
      - name: normalize Python Version
        run: |
          PYTHON_VERSION=$(echo ${{ matrix.python-version }} | tr -d '.')
          echo "PYTHON_VERSION=${PYTHON_VERSION}" >> "$GITHUB_ENV"
      - name: Configure SAR name
        run: |
          if [[ "${{ inputs.stage }}" == "BETA" ]]; then
            SAR_NAME="test-${SAR_NAME}"
          fi
          ARCH_NAME=$(echo ${{ matrix.architecture }} | tr -d '_')
          SAR_NAME="${SAR_NAME}-python${{env.PYTHON_VERSION}}-${ARCH_NAME}"
          echo SAR_NAME="${SAR_NAME}" >> "$GITHUB_ENV"
      - name: Normalize semantic version
        id: semantic-version # v2.0.0a0 -> v2.0.0-a0
        env:
          VERSION: ${{ inputs.package-version }}
        run: |
          # VERSION="${VERSION/a/-a}"
          VERSION="3.0.0"
          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
      - name: Prepare SAR App
        env:
          VERSION: ${{ steps.semantic-version.outputs.VERSION }}
        run: |
          # From the generated LayerStack cdk.out artifact, find the layer asset path for the correct architecture.
          # We'll use this as the source directory of our SAR. This way we are re-using the same layer asset for our SAR.
          PYTHON_VERSION=$(echo ${{ matrix.python-version }} | tr -d '.')
          asset=$(jq -jc '.Resources[] | select(.Properties.CompatibleArchitectures == ["${{ matrix.architecture }}"]) | .Metadata."aws:asset:path"' "cdk.out/LayerV3Stack-python${PYTHON_VERSION}.template.json")

          # fill in the SAR SAM template
          sed \
            -e "s|<VERSION>|${VERSION}|g" \
            -e "s/<SAR_APP_NAME>/${{ env.SAR_NAME }}/g" \
            -e "s|<LAYER_CONTENT_PATH>|./cdk.out/$asset|g" \
            -e "s|<PYTHON_RUNTIME>|${{ matrix.python-version }}|g" \
            -e "s|<ARCHITECTURE>|${{ matrix.architecture }}|g" \
            layer/sar/template.txt > template.yml

          # SAR needs a README and a LICENSE, so just copy the ones from the repo
          cp README.md LICENSE "./cdk.out/$asset/"
      - name: Deploy SAR
        run: |
          # Debug purposes
          cat template.yml

          # Package the SAR to our SAR S3 bucket, and publish it
          sam package --template-file template.yml --output-template-file packaged.yml --s3-bucket ${{ secrets.AWS_SAR_S3_BUCKET_V3 }}
          sam publish --template packaged.yml --region "$AWS_REGION"
      - name: Deploy BETA canary
        if: ${{ inputs.stage == 'BETA' }}
        run: |
          ARCH_NAME=$(echo ${{ matrix.architecture }} | tr -d '_')
          TEST_STACK_NAME="${TEST_STACK_NAME}-python${{env.PYTHON_VERSION}}-${ARCH_NAME}"

          echo "Check if stack does not exist"
          stack_exists=$(aws cloudformation list-stacks --query "StackSummaries[?(StackName == '$TEST_STACK_NAME' && StackStatus == 'CREATE_COMPLETE')].{StackId:StackId, StackName:StackName, CreationTime:CreationTime, StackStatus:StackStatus}" --output text)

          if [[ -n "$stack_exists" ]] ; then
            echo "Found test deployment stack, removing..."
            aws cloudformation delete-stack --stack-name "$TEST_STACK_NAME"
            aws cloudformation wait stack-delete-complete --stack-name "$TEST_STACK_NAME"
          fi

          echo "Creating canary stack"
          echo "Stack name: $TEST_STACK_NAME"
          aws serverlessrepo create-cloud-formation-change-set \
            --application-id arn:aws:serverlessrepo:${{ env.AWS_REGION }}:${{ steps.aws-credentials-sar-role.outputs.aws-account-id }}:applications/${{ env.SAR_NAME }} \
            --stack-name "${TEST_STACK_NAME/serverlessrepo-/}" \
            --capabilities CAPABILITY_NAMED_IAM

          CHANGE_SET_ID=$(aws cloudformation list-change-sets --stack-name "$TEST_STACK_NAME" --query 'Summaries[*].ChangeSetId' --output text)
          aws cloudformation wait change-set-create-complete --change-set-name "$CHANGE_SET_ID"
          aws cloudformation execute-change-set --change-set-name "$CHANGE_SET_ID"
          aws cloudformation wait stack-create-complete --stack-name "$TEST_STACK_NAME"

          echo "Waiting until stack deployment completes..."

          echo "Exit with error if stack is not in CREATE_COMPLETE"
          stack_exists=$(aws cloudformation list-stacks --query "StackSummaries[?(StackName == '$TEST_STACK_NAME' && StackStatus == 'CREATE_COMPLETE')].{StackId:StackId, StackName:StackName, CreationTime:CreationTime, StackStatus:StackStatus}")
          if [[ -z "$stack_exists" ]] ; then
            echo "Could find successful deployment, exit error..."
            exit 1
          fi
          echo "Deployment successful"
      - name: Publish SAR
        if: ${{ inputs.stage == 'PROD' }}
        run: |
          # wait until SAR registers the app, otherwise it fails to make it public
          sleep 15
          echo "Make SAR app public"
          aws serverlessrepo put-application-policy \
            --application-id arn:aws:serverlessrepo:${{ env.AWS_REGION }}:${{ steps.aws-credentials-sar-role.outputs.aws-account-id }}:applications/${{ env.SAR_NAME }} \
            --statements Principals='*',Actions=Deploy
